apiVersion: v1
kind: Secret
metadata:
  name: db
  annotations:
    avp.kubernetes.io/path: "secret/data/immich"
stringData:
  POSTGRES_PASSWORD: <DB_PASSWORD>
  POSTGRES_USER: <DB_USERNAME>
  POSTGRES_DB: <DB_DATABASE_NAME>
---
apiVersion: v1
kind: Secret
metadata:
  name: server
  annotations:
    avp.kubernetes.io/path: "secret/data/immich"
stringData:
  DB_PASSWORD: <DB_PASSWORD>
  DB_USERNAME: <DB_USERNAME>
  DB_DATABASE_NAME: <DB_DATABASE_NAME>
