apiVersion: v1
kind: ConfigMap
metadata:
  name: server
data:
  REDIS_HOSTNAME: "immich-redis"
  REDIS_PORT: "6379"
  DB_HOSTNAME: "immich-postgres"
  UPLOAD_LOCATION: "./library"
  DB_DATA_LOCATION: "./postgres"