apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - ../base
  - avp-cm-config.yaml
  - avp-secret.yaml
  - cm-server.yaml
  - hpa.yaml

configMapGenerator:
  - name: ml-config
    files:
      - cm-ml-config.yaml

transformers:
  - tf-label.yaml
  - tf-sp.yaml

